// export const SET_TAG = '[object Set]'
// export const MAP_TAG = '[object Map]'

export const argsTag = '[object Arguments]'
export const arrayTag = '[object Array]'
export const boolTag = '[object Boolean]'
export const dateTag = '[object Date]'
export const errorTag = '[object Error]'
export const mapTag = '[object Map]'
export const numberTag = '[object Number]'
export const objectTag = '[object Object]'
export const regexpTag = '[object RegExp]'
export const setTag = '[object Set]'
export const stringTag = '[object String]'
export const symbolTag = '[object Symbol]'
export const weakMapTag = '[object WeakMap]'

export const arrayBufferTag = '[object ArrayBuffer]'
export const dataViewTag = '[object DataView]'
export const float32Tag = '[object Float32Array]'
export const float64Tag = '[object Float64Array]'
export const int8Tag = '[object Int8Array]'
export const int16Tag = '[object Int16Array]'
export const int32Tag = '[object Int32Array]'
export const uint8Tag = '[object Uint8Array]'
export const uint8ClampedTag = '[object Uint8ClampedArray]'
export const uint16Tag = '[object Uint16Array]'
export const uint32Tag = '[object Uint32Array]'
